name: Deploy to EC2

on:
  push:
    branches: [ "master" ]
  
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install PM2
      run: |
        npm install -g pm2

    - name: Install dependencies
      run: npm ci

    - name: Set environment variables
      run: |
        touch .env
        echo "${{ secrets.PROD }}" > .env

    - name: Restart Node.js application with PM2
      run: |
        pm2 restart Backend
