name: Deploy to EC2

on:
  push:
    branches:
      - master  # Change this to your desired branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Change this to your desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables
        run: |
          touch .env
          echo "${{ secrets.PROD }}" > .env

      - name: SSH into EC2 and restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/app
            pm2 restart Backend  # Adjust this command as needed
